/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.PopUp;

import view.login.Login;
import java.awt.Color;

/**
 *
 * @author luis_
 */
public class PopUp_Erro_login extends javax.swing.JFrame {

 
         private int  xMouse;
      private int yMouse;
      
    public PopUp_Erro_login() {
        initComponents();
        setBackground(new Color(255,255,255,0));
        /*Login.enviar.setEnabled(false);
        Login.Usuario.setEnabled(false);
        Login.senha.setEnabled(false);
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JPanel();
        esquerd_panel = new javax.swing.JPanel();
        titulo_usuario = new javax.swing.JLabel();
        titulo_senha = new javax.swing.JLabel();
        Fechar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Principal.setBackground(new java.awt.Color(255, 255, 255));
        Principal.setBorder(new javax.swing.border.MatteBorder(null));
        Principal.setOpaque(false);
        Principal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PrincipalMouseDragged(evt);
            }
        });
        Principal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PrincipalMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PrincipalMousePressed(evt);
            }
        });
        Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        esquerd_panel.setBackground(new java.awt.Color(255, 255, 255));
        esquerd_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_usuario.setBackground(new java.awt.Color(255, 255, 255));
        titulo_usuario.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        titulo_usuario.setForeground(new java.awt.Color(255, 0, 0));
        titulo_usuario.setText("Erro: Incorret password or username");
        esquerd_panel.add(titulo_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        titulo_senha.setBackground(new java.awt.Color(255, 255, 255));
        titulo_senha.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        titulo_senha.setForeground(new java.awt.Color(255, 0, 0));
        titulo_senha.setText("Try again");
        esquerd_panel.add(titulo_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, 20));

        Principal.add(esquerd_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-463, 30, 463, 70));

        Fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-delete-24 (1).png"))); // NOI18N
        Fechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FecharMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FecharMouseExited(evt);
            }
        });
        Principal.add(Fechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 30, -1));

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Principal.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 463, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FecharMouseClicked
//       Login.enviar.setEnabled(true);
//        Login.Usuario.setEnabled(true);
//        Login.senha.setEnabled(true);
//        Login.Usuario.setText("");
//        Login.senha.setText("");
        dispose();
    }//GEN-LAST:event_FecharMouseClicked

    private void FecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FecharMouseEntered
        Fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-multiply-filled-24 (1).png")));
    }//GEN-LAST:event_FecharMouseEntered

    private void FecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FecharMouseExited
        Fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-delete-24 (1).png")));
    }//GEN-LAST:event_FecharMouseExited

    private void PrincipalMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrincipalMouseDragged

    }//GEN-LAST:event_PrincipalMouseDragged

    private void PrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrincipalMouseEntered

    }//GEN-LAST:event_PrincipalMouseEntered

    private void PrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrincipalMousePressed

    }//GEN-LAST:event_PrincipalMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

           int position = esquerd_panel.getX();
              Animacion.Animacion.mover_derecha(position,0, 2, 3, esquerd_panel); 
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUp_Erro_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUp_Erro_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUp_Erro_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUp_Erro_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopUp_Erro_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fechar;
    private javax.swing.JPanel Principal;
    private javax.swing.JPanel esquerd_panel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel titulo_senha;
    private javax.swing.JLabel titulo_usuario;
    // End of variables declaration//GEN-END:variables
}
