
package view.Gerente;

import view.Funcionario.Home;
import model.Troca;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

public class Prin_gerente extends javax.swing.JFrame {

  private int xMouse,yMouse;
    public Prin_gerente() {
        initComponents();
        seticon();
        setBackground(new Color(0,0,0,0));
     
        Home ho = new Home();
        Troca tro = new Troca(Principal, ho);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sub_menu = new javax.swing.JPanel();
        imagem = new javax.swing.JLabel();
        jldata = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();
        todos_reservados = new javax.swing.JLabel();
        copia__não = new javax.swing.JLabel();
        usuario1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        Cadastrar = new javax.swing.JButton();
        Administrar_fun = new javax.swing.JButton();
        registrar_carro = new javax.swing.JButton();
        tabela_carro = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        promocoes = new javax.swing.JButton();
        degrade = new keeptoo.KGradientPanel();
        email = new javax.swing.JLabel();
        twitter = new javax.swing.JLabel();
        instagram = new javax.swing.JLabel();
        facebook = new javax.swing.JLabel();
        Principal = new javax.swing.JPanel();
        topo = new javax.swing.JPanel();
        fechar_X = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        topo1 = new javax.swing.JPanel();
        BoMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 100));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Sub_menu.setBackground(new java.awt.Color(255, 124, 100));
        Sub_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-usuário-de-gênero-neutro-96 (1).png"))); // NOI18N
        imagem.setText("jLabel1");
        Sub_menu.add(imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 101, -1));

        jldata.setBackground(new java.awt.Color(255, 124, 100));
        jldata.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jldata.setForeground(new java.awt.Color(255, 255, 255));
        jldata.setText("dd/MM/yyyy");
        jldata.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jldataComponentShown(evt);
            }
        });
        Sub_menu.add(jldata, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        texto.setBackground(new java.awt.Color(255, 124, 100));
        texto.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));
        texto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-direito-de-cópia-10.png"))); // NOI18N
        texto.setText("2019 Vilet's Team .");
        texto.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                textoComponentShown(evt);
            }
        });
        Sub_menu.add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 120, -1));

        todos_reservados.setBackground(new java.awt.Color(255, 124, 100));
        todos_reservados.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        todos_reservados.setForeground(new java.awt.Color(255, 255, 255));
        todos_reservados.setText("Todos os direitos reservados ");
        todos_reservados.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                todos_reservadosComponentShown(evt);
            }
        });
        Sub_menu.add(todos_reservados, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, -1, -1));

        copia__não.setBackground(new java.awt.Color(255, 124, 100));
        copia__não.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        copia__não.setForeground(new java.awt.Color(255, 255, 255));
        copia__não.setText("Copia não comédia");
        copia__não.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                copia__nãoComponentShown(evt);
            }
        });
        Sub_menu.add(copia__não, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, -1, -1));

        usuario1.setBackground(new java.awt.Color(255, 124, 100));
        usuario1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        usuario1.setForeground(new java.awt.Color(255, 255, 255));
        usuario1.setText("Administrador");
        usuario1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                usuario1ComponentShown(evt);
            }
        });
        Sub_menu.add(usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        Menu.setBackground(new java.awt.Color(0, 0, 0));
        Menu.setOpaque(false);

        Cadastrar.setBackground(new java.awt.Color(51, 51, 51));
        Cadastrar.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        Cadastrar.setForeground(new java.awt.Color(102, 102, 102));
        Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-client-management-filled-24.png"))); // NOI18N
        Cadastrar.setToolTipText("Cadastrar cliente");
        Cadastrar.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        Cadastrar.setContentAreaFilled(false);
        Cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CadastrarMouseExited(evt);
            }
        });
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        Administrar_fun.setBackground(new java.awt.Color(51, 51, 51));
        Administrar_fun.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        Administrar_fun.setForeground(new java.awt.Color(102, 102, 102));
        Administrar_fun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-admin-settings-male-filled-24.png"))); // NOI18N
        Administrar_fun.setToolTipText("Catálogo");
        Administrar_fun.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        Administrar_fun.setContentAreaFilled(false);
        Administrar_fun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Administrar_fun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Administrar_funMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Administrar_funMouseExited(evt);
            }
        });
        Administrar_fun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Administrar_funActionPerformed(evt);
            }
        });

        registrar_carro.setBackground(new java.awt.Color(51, 51, 51));
        registrar_carro.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        registrar_carro.setForeground(new java.awt.Color(102, 102, 102));
        registrar_carro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-mais-24.png"))); // NOI18N
        registrar_carro.setToolTipText("Adicionar carro");
        registrar_carro.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        registrar_carro.setContentAreaFilled(false);
        registrar_carro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrar_carro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrar_carroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrar_carroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrar_carroMouseExited(evt);
            }
        });

        tabela_carro.setBackground(new java.awt.Color(51, 51, 51));
        tabela_carro.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        tabela_carro.setForeground(new java.awt.Color(102, 102, 102));
        tabela_carro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-car-filled-24.png"))); // NOI18N
        tabela_carro.setToolTipText("Gerenciar carros");
        tabela_carro.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        tabela_carro.setContentAreaFilled(false);
        tabela_carro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabela_carro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabela_carroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tabela_carroMouseExited(evt);
            }
        });
        tabela_carro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabela_carroActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(51, 51, 51));
        logout.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        logout.setForeground(new java.awt.Color(102, 102, 102));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-shutdown-24.png"))); // NOI18N
        logout.setToolTipText("Logout");
        logout.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        logout.setContentAreaFilled(false);
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        promocoes.setBackground(new java.awt.Color(51, 51, 51));
        promocoes.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        promocoes.setForeground(new java.awt.Color(102, 102, 102));
        promocoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-promoção-carrinho-de-compras-24.png"))); // NOI18N
        promocoes.setToolTipText("Gerenciar promoções");
        promocoes.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        promocoes.setContentAreaFilled(false);
        promocoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        promocoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                promocoesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                promocoesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Administrar_fun, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(Cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(registrar_carro, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(tabela_carro, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(promocoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addComponent(Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Administrar_fun, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrar_carro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabela_carro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(promocoes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        Sub_menu.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 50, 330));

        degrade.setBackground(new java.awt.Color(255, 255, 255));
        degrade.setEndColor(new java.awt.Color(0, 255, 255));
        degrade.setStartColor(new java.awt.Color(0, 0, 0));

        email.setBackground(new java.awt.Color(255, 124, 100));
        email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("viletsTeam@gmail.com");
        email.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                emailComponentShown(evt);
            }
        });
        degrade.add(email);
        email.setBounds(40, 530, 150, 15);

        twitter.setBackground(new java.awt.Color(255, 124, 100));
        twitter.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        twitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-twitter-filled-24.png"))); // NOI18N
        twitter.setToolTipText("Follow us on twitter");
        twitter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        twitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twitterMouseClicked(evt);
            }
        });
        twitter.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                twitterComponentShown(evt);
            }
        });
        degrade.add(twitter);
        twitter.setBounds(120, 510, 24, 24);

        instagram.setBackground(new java.awt.Color(255, 124, 100));
        instagram.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        instagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-instagram-filled-24_.png"))); // NOI18N
        instagram.setToolTipText("Folow us on Instagram ");
        instagram.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        instagram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instagramMouseClicked(evt);
            }
        });
        instagram.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                instagramComponentShown(evt);
            }
        });
        degrade.add(instagram);
        instagram.setBounds(90, 510, 24, 24);

        facebook.setBackground(new java.awt.Color(255, 124, 100));
        facebook.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        facebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-facebook-filled-24.png"))); // NOI18N
        facebook.setToolTipText("See Facebook page");
        facebook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        facebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facebookMouseClicked(evt);
            }
        });
        facebook.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                facebookComponentShown(evt);
            }
        });
        degrade.add(facebook);
        facebook.setBounds(60, 510, 24, 24);

        Sub_menu.add(degrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 600));

        Principal.setBackground(new java.awt.Color(0, 0, 0));
        Principal.setLayout(new javax.swing.BoxLayout(Principal, javax.swing.BoxLayout.LINE_AXIS));

        topo.setBackground(new java.awt.Color(0, 0, 0));
        topo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topoMouseDragged(evt);
            }
        });
        topo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topoMousePressed(evt);
            }
        });
        topo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fechar_X.setBackground(new java.awt.Color(255, 0, 0));
        fechar_X.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fechar_X.setForeground(new java.awt.Color(102, 102, 102));
        fechar_X.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechar_X.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-delete-24 (1) - Copia.png"))); // NOI18N
        fechar_X.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fechar_X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fechar_XMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fechar_XMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fechar_XMouseExited(evt);
            }
        });
        topo.add(fechar_X, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 34, 30));

        minimizar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        minimizar.setForeground(new java.awt.Color(102, 102, 102));
        minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-compress-filled-24 - Copia.png"))); // NOI18N
        minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizarMouseExited(evt);
            }
        });
        topo.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 34, 30));

        topo1.setBackground(new java.awt.Color(0, 0, 0));
        topo1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topo1MouseDragged(evt);
            }
        });
        topo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topo1MousePressed(evt);
            }
        });
        topo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-menu-24 (1) - Copia.png"))); // NOI18N
        BoMenu.setToolTipText("Menu");
        BoMenu.setBorder(null);
        BoMenu.setContentAreaFilled(false);
        BoMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BoMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BoMenu.setVerifyInputWhenFocusTarget(false);
        BoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BoMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BoMenuMouseExited(evt);
            }
        });
        BoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoMenuActionPerformed(evt);
            }
        });
        topo1.add(BoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, 30));

        topo.add(topo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 231, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Sub_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(topo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sub_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jldataComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jldataComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jldataComponentShown

    private void fechar_XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechar_XMouseClicked
        this.dispose();
    }//GEN-LAST:event_fechar_XMouseClicked

    private void fechar_XMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechar_XMouseEntered
               fechar_X.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-multiply-filled-24 (1).png")));
    }//GEN-LAST:event_fechar_XMouseEntered

    private void fechar_XMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechar_XMouseExited
 fechar_X.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-delete-24 (1) - Copia.png")));
    }//GEN-LAST:event_fechar_XMouseExited

    private void BoMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoMenuMouseEntered
        BoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-menu-24 (1).png")));
    }//GEN-LAST:event_BoMenuMouseEntered

    private void BoMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoMenuMouseExited
        BoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-menu-24 (1) - Copia.png" )));
    }//GEN-LAST:event_BoMenuMouseExited

    private void BoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoMenuActionPerformed
      int position = BoMenu.getX();
        if(position> 5){
            Animacion.Animacion.mover_izquierda(position,5, 20, 4, BoMenu);
            Animacion.Animacion.mover_izquierda(0,-50, 20, 4, Menu);

        }
        else{
            Animacion.Animacion.mover_derecha(position,45, 20, 4, BoMenu);
            Animacion.Animacion.mover_derecha(-51,0, 20, 4, Menu);

        }

    }//GEN-LAST:event_BoMenuActionPerformed

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
       this.setState(Prin_gerente.ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked

    private void minimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseEntered
  minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-compress-filled-24.png")));    }//GEN-LAST:event_minimizarMouseEntered

    private void minimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseExited
                minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-compress-filled-24 - Copia.png")));

    }//GEN-LAST:event_minimizarMouseExited

    private void topoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topoMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_topoMouseDragged

    private void topoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topoMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_topoMousePressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
                int position = BoMenu.getX();
        if(position>4){
     Date data= new Date();
        SimpleDateFormat form= new SimpleDateFormat("dd/MM/yyy");
        jldata.setText(form.format(data));
        
     //Hora
     /*Timer timer = new Timer(1000, (ActionListener) new Prin_gerente.hora());
     timer.start();*/}
        else{}
    }//GEN-LAST:event_formWindowActivated

    private void copia__nãoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_copia__nãoComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_copia__nãoComponentShown

    private void todos_reservadosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_todos_reservadosComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_todos_reservadosComponentShown

    private void emailComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_emailComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_emailComponentShown

    private void facebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facebookMouseClicked
        try {
            Runtime.getRuntime().exec("cmd.exe /C start " + "https://www.facebook.com/Vilets-Team-2265673113688326/?modal=admin_todo_tour");
        }catch (IOException ex) {
            System.out.println(ex.getMessage()); }

    }//GEN-LAST:event_facebookMouseClicked

    private void facebookComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_facebookComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_facebookComponentShown

    private void instagramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instagramMouseClicked
        try {
            Runtime.getRuntime().exec("cmd.exe /C start " + "https://www.instagram.com/?hl=pt-br");
        }catch (IOException ex) {
            System.out.println(ex.getMessage()); }
    }//GEN-LAST:event_instagramMouseClicked

    private void instagramComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_instagramComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_instagramComponentShown

    private void twitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twitterMouseClicked
        try {
            Runtime.getRuntime().exec("cmd.exe /C start " + "https://twitter.com/");
        }catch (IOException ex) {
            System.out.println(ex.getMessage()); }
    }//GEN-LAST:event_twitterMouseClicked

    private void twitterComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_twitterComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_twitterComponentShown

    private void textoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_textoComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_textoComponentShown

    private void topo1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topo1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_topo1MouseDragged

    private void topo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topo1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_topo1MousePressed

    private void usuario1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_usuario1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_usuario1ComponentShown

    private void CadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarMouseClicked
        Registrar_funcionario in = new Registrar_funcionario();
        Troca tro = new Troca(Principal, in);
    }//GEN-LAST:event_CadastrarMouseClicked

    private void CadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarMouseEntered
        Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-client-management-filled-24.gif")));
    }//GEN-LAST:event_CadastrarMouseEntered

    private void CadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarMouseExited
        Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-client-management-filled-24.png")));
    }//GEN-LAST:event_CadastrarMouseExited

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastrarActionPerformed

    private void Administrar_funMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Administrar_funMouseEntered
        Administrar_fun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-admin-settings-male-filled-24.gif")));
    }//GEN-LAST:event_Administrar_funMouseEntered

    private void Administrar_funMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Administrar_funMouseExited
        Administrar_fun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-admin-settings-male-filled-24.png")));
    }//GEN-LAST:event_Administrar_funMouseExited

    private void Administrar_funActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Administrar_funActionPerformed
 Tabela_funcionario in = new Tabela_funcionario();
        Troca tro = new Troca(Principal, in);
    }//GEN-LAST:event_Administrar_funActionPerformed

    private void registrar_carroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrar_carroMouseClicked
         Registrar_veiculo in = new Registrar_veiculo();
        Troca tro = new Troca(Principal, in);
    }//GEN-LAST:event_registrar_carroMouseClicked

    private void registrar_carroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrar_carroMouseEntered
        registrar_carro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-mais-24.gif"))); // NOI18N
    }//GEN-LAST:event_registrar_carroMouseEntered

    private void registrar_carroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrar_carroMouseExited
        registrar_carro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-mais-24.png"))); // NOI18N
    }//GEN-LAST:event_registrar_carroMouseExited

    private void tabela_carroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_carroMouseEntered
        tabela_carro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-car-filled-24.gif"))); // NOI18N
    }//GEN-LAST:event_tabela_carroMouseEntered

    private void tabela_carroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_carroMouseExited
        tabela_carro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-car-filled-24.png"))); // NOI18N
    }//GEN-LAST:event_tabela_carroMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        this.dispose();
        view.login.Login log = new view.login.Login();
        log.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-shutdown-24.gif")));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-shutdown-24.png")));
    }//GEN-LAST:event_logoutMouseExited

    private void promocoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_promocoesMouseEntered
       promocoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-promoção-carrinho-de-compras-24.gif"))); // NOI18N

    }//GEN-LAST:event_promocoesMouseEntered

    private void promocoesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_promocoesMouseExited
        promocoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-promoção-carrinho-de-compras-24.png"))); // NOI18N
    }//GEN-LAST:event_promocoesMouseExited

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void tabela_carroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabela_carroActionPerformed
         Tabela_veiculo in = new Tabela_veiculo();
        Troca tro = new Troca(Principal, in);
    }//GEN-LAST:event_tabela_carroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prin_gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prin_gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prin_gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prin_gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prin_gerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Administrar_fun;
    private javax.swing.JButton BoMenu;
    private javax.swing.JButton Cadastrar;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Principal;
    public static javax.swing.JPanel Sub_menu;
    public javax.swing.JLabel copia__não;
    private keeptoo.KGradientPanel degrade;
    public javax.swing.JLabel email;
    public javax.swing.JLabel facebook;
    private javax.swing.JLabel fechar_X;
    private javax.swing.JLabel imagem;
    public javax.swing.JLabel instagram;
    public javax.swing.JLabel jldata;
    private javax.swing.JButton logout;
    private javax.swing.JLabel minimizar;
    private javax.swing.JButton promocoes;
    private javax.swing.JButton registrar_carro;
    private javax.swing.JButton tabela_carro;
    public javax.swing.JLabel texto;
    public javax.swing.JLabel todos_reservados;
    private javax.swing.JPanel topo;
    private javax.swing.JPanel topo1;
    public javax.swing.JLabel twitter;
    public javax.swing.JLabel usuario1;
    // End of variables declaration//GEN-END:variables

  /* class hora implements ActionListener{
            @Override
            public void actionPerformed(ActionEvent e){
                Calendar now = Calendar.getInstance();
                int position = BoMenu.getX();
                if(position > 5){
                    jlhora.setText(String.format("00:00"));                        

        }else{
    jlhora.setText(String.format("%1$tH:%1tM",now));}}        
}*/

    private void seticon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icon/Nova_logo.png")));
    
    }
    public void minimizar(){
    setState(Prin_gerente.ICONIFIED);
    }

}
