/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Gerente;

/**
 *
 * @author Aluno 22
 */
public class Promocoes extends javax.swing.JPanel {

    /**
     * Creates new form Promocoes
     */
    public Promocoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JPanel();
        Part2 = new javax.swing.JPanel();
        cidade = new javax.swing.JTextField();
        titulo_cidade = new javax.swing.JLabel();
        cpf = new javax.swing.JFormattedTextField();
        titulo_cpf = new javax.swing.JLabel();
        rg = new javax.swing.JFormattedTextField();
        titulo_rg = new javax.swing.JLabel();
        pis = new javax.swing.JFormattedTextField();
        titulo_pis = new javax.swing.JLabel();
        estado = new javax.swing.JTextField();
        titulo_estado = new javax.swing.JLabel();
        telefone = new javax.swing.JFormattedTextField();
        titulo_telefone = new javax.swing.JLabel();
        data_nasc = new javax.swing.JFormattedTextField();
        titulo_data_nasc = new javax.swing.JLabel();
        titulo_nome1 = new javax.swing.JLabel();
        nome_completo = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        usuario_text = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        titulo_email = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        esquerd_panel = new javax.swing.JPanel();
        titul0 = new javax.swing.JLabel();
        limpar = new javax.swing.JButton();
        Tabela_scroll = new javax.swing.JScrollPane();
        Tabela = new rojerusan.RSTableMetro();
        atualizar = new javax.swing.JButton();

        Principal.setBackground(new java.awt.Color(0, 0, 0));
        Principal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PrincipalMouseEntered(evt);
            }
        });
        Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Part2.setBackground(new java.awt.Color(0, 0, 0));
        Part2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Part2MouseEntered(evt);
            }
        });
        Part2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cidade.setBackground(new java.awt.Color(0, 255, 255));
        cidade.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        cidade.setForeground(new java.awt.Color(255, 0, 0));
        cidade.setToolTipText("Insira sua cidade");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShadowColor(new java.awt.Color(0, 255, 255));
        dropShadowBorder1.setShadowOpacity(1.0F);
        dropShadowBorder1.setShadowSize(10);
        cidade.setBorder(dropShadowBorder1);
        cidade.setCaretColor(new java.awt.Color(255, 0, 0));
        cidade.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        cidade.setOpaque(false);
        Part2.add(cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 246, 51));

        titulo_cidade.setBackground(new java.awt.Color(0, 255, 255));
        titulo_cidade.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        titulo_cidade.setForeground(new java.awt.Color(255, 255, 255));
        titulo_cidade.setText("Cidade:");
        Part2.add(titulo_cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, -1, -1));

        cpf.setBackground(new java.awt.Color(0, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShadowColor(new java.awt.Color(0, 255, 255));
        dropShadowBorder2.setShadowOpacity(1.0F);
        dropShadowBorder2.setShadowSize(10);
        cpf.setBorder(dropShadowBorder2);
        cpf.setForeground(new java.awt.Color(255, 0, 0));
        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpf.setToolTipText("Insira seu CPF");
        cpf.setCaretColor(new java.awt.Color(255, 0, 0));
        cpf.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        cpf.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        cpf.setOpaque(false);
        Part2.add(cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 180, 51));

        titulo_cpf.setBackground(new java.awt.Color(0, 255, 255));
        titulo_cpf.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        titulo_cpf.setForeground(new java.awt.Color(255, 255, 255));
        titulo_cpf.setText("CPF:");
        Part2.add(titulo_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        rg.setBackground(new java.awt.Color(0, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShadowColor(new java.awt.Color(0, 255, 255));
        dropShadowBorder3.setShadowOpacity(1.0F);
        dropShadowBorder3.setShadowSize(10);
        rg.setBorder(dropShadowBorder3);
        rg.setForeground(new java.awt.Color(255, 0, 0));
        try {
            rg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########.#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        rg.setToolTipText("Insira seu RG");
        rg.setCaretColor(new java.awt.Color(255, 0, 0));
        rg.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        rg.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        rg.setOpaque(false);
        Part2.add(rg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 180, 51));

        titulo_rg.setBackground(new java.awt.Color(0, 255, 255));
        titulo_rg.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        titulo_rg.setForeground(new java.awt.Color(255, 255, 255));
        titulo_rg.setText("RG:");
        Part2.add(titulo_rg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        pis.setBackground(new java.awt.Color(0, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder4 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder4.setShadowColor(new java.awt.Color(0, 255, 255));
        dropShadowBorder4.setShadowOpacity(1.0F);
        dropShadowBorder4.setShadowSize(10);
        pis.setBorder(dropShadowBorder4);
        pis.setForeground(new java.awt.Color(255, 0, 0));
        try {
            pis.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.#####.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pis.setToolTipText("Insira o seu PIS");
        pis.setCaretColor(new java.awt.Color(255, 0, 0));
        pis.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        pis.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        pis.setOpaque(false);
        pis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pisActionPerformed(evt);
            }
        });
        Part2.add(pis, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 180, 51));

        titulo_pis.setBackground(new java.awt.Color(0, 255, 255));
        titulo_pis.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        titulo_pis.setForeground(new java.awt.Color(255, 255, 255));
        titulo_pis.setText("Nº PIS:");
        Part2.add(titulo_pis, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 70, -1));

        estado.setBackground(new java.awt.Color(0, 255, 255));
        estado.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        estado.setForeground(new java.awt.Color(255, 0, 0));
        estado.setToolTipText("Insira seu Estado");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder5 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder5.setShadowColor(new java.awt.Color(0, 255, 255));
        dropShadowBorder5.setShadowOpacity(1.0F);
        dropShadowBorder5.setShadowSize(10);
        estado.setBorder(dropShadowBorder5);
        estado.setCaretColor(new java.awt.Color(255, 0, 0));
        estado.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        estado.setOpaque(false);
        Part2.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 246, 51));

        titulo_estado.setBackground(new java.awt.Color(0, 255, 255));
        titulo_estado.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        titulo_estado.setForeground(new java.awt.Color(255, 255, 255));
        titulo_estado.setText("Estado:");
        Part2.add(titulo_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        telefone.setBackground(new java.awt.Color(0, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder6 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder6.setShadowColor(new java.awt.Color(0, 255, 255));
        dropShadowBorder6.setShadowOpacity(1.0F);
        dropShadowBorder6.setShadowSize(10);
        telefone.setBorder(dropShadowBorder6);
        telefone.setForeground(new java.awt.Color(255, 0, 0));
        try {
            telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+##(##)#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefone.setToolTipText("Insira seu telefone");
        telefone.setCaretColor(new java.awt.Color(255, 0, 0));
        telefone.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        telefone.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        telefone.setOpaque(false);
        Part2.add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 180, 51));

        titulo_telefone.setBackground(new java.awt.Color(0, 255, 255));
        titulo_telefone.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        titulo_telefone.setForeground(new java.awt.Color(255, 255, 255));
        titulo_telefone.setText("Telefone:");
        Part2.add(titulo_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        data_nasc.setBackground(new java.awt.Color(0, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder7 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder7.setShadowColor(new java.awt.Color(0, 255, 255));
        dropShadowBorder7.setShadowOpacity(1.0F);
        dropShadowBorder7.setShadowSize(10);
        data_nasc.setBorder(dropShadowBorder7);
        data_nasc.setForeground(new java.awt.Color(255, 0, 0));
        try {
            data_nasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        data_nasc.setToolTipText("Insira sua data de nascimento");
        data_nasc.setCaretColor(new java.awt.Color(255, 0, 0));
        data_nasc.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        data_nasc.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        data_nasc.setOpaque(false);
        Part2.add(data_nasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 120, 51));

        titulo_data_nasc.setBackground(new java.awt.Color(0, 255, 255));
        titulo_data_nasc.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        titulo_data_nasc.setForeground(new java.awt.Color(255, 255, 255));
        titulo_data_nasc.setText("Data de Nascimento:");
        Part2.add(titulo_data_nasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        titulo_nome1.setBackground(new java.awt.Color(0, 255, 255));
        titulo_nome1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        titulo_nome1.setForeground(new java.awt.Color(255, 255, 255));
        titulo_nome1.setText("Nome completo:");
        Part2.add(titulo_nome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        nome_completo.setBackground(new java.awt.Color(0, 255, 255));
        nome_completo.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        nome_completo.setForeground(new java.awt.Color(255, 0, 0));
        nome_completo.setToolTipText("Insira seu nome completo");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder8 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder8.setShadowColor(new java.awt.Color(0, 255, 255));
        dropShadowBorder8.setShadowOpacity(1.0F);
        dropShadowBorder8.setShadowSize(10);
        nome_completo.setBorder(dropShadowBorder8);
        nome_completo.setCaretColor(new java.awt.Color(255, 0, 0));
        nome_completo.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        nome_completo.setOpaque(false);
        Part2.add(nome_completo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 246, 51));

        email.setBackground(new java.awt.Color(0, 255, 255));
        email.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 0, 0));
        email.setToolTipText("Insira aqui seu Email");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder9 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder9.setShadowColor(new java.awt.Color(0, 255, 255));
        dropShadowBorder9.setShadowOpacity(1.0F);
        dropShadowBorder9.setShadowSize(10);
        email.setBorder(dropShadowBorder9);
        email.setCaretColor(new java.awt.Color(255, 0, 0));
        email.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        email.setOpaque(false);
        Part2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 246, 51));

        usuario_text.setBackground(new java.awt.Color(0, 255, 255));
        usuario_text.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        usuario_text.setForeground(new java.awt.Color(255, 255, 255));
        usuario_text.setText("Usuário:");
        Part2.add(usuario_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        usuario.setBackground(new java.awt.Color(0, 255, 255));
        usuario.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        usuario.setForeground(new java.awt.Color(255, 0, 0));
        usuario.setToolTipText("Crie seu usuário");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder10 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder10.setShadowColor(new java.awt.Color(0, 255, 255));
        dropShadowBorder10.setShadowOpacity(1.0F);
        dropShadowBorder10.setShadowSize(10);
        usuario.setBorder(dropShadowBorder10);
        usuario.setCaretColor(new java.awt.Color(255, 0, 0));
        usuario.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        usuario.setOpaque(false);
        Part2.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 246, 51));

        titulo_email.setBackground(new java.awt.Color(0, 255, 255));
        titulo_email.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        titulo_email.setForeground(new java.awt.Color(255, 255, 255));
        titulo_email.setText("Email:");
        Part2.add(titulo_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        voltar.setBackground(new java.awt.Color(0, 255, 255));
        voltar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        voltar.setForeground(new java.awt.Color(255, 255, 255));
        voltar.setText("Voltar");
        voltar.setBorder(null);
        voltar.setContentAreaFilled(false);
        voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltar.setOpaque(true);
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        Part2.add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 120, 40));

        alterar.setBackground(new java.awt.Color(0, 255, 255));
        alterar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        alterar.setForeground(new java.awt.Color(255, 255, 255));
        alterar.setText("Alterar");
        alterar.setBorder(null);
        alterar.setContentAreaFilled(false);
        alterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alterar.setOpaque(true);
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });
        Part2.add(alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, 120, 40));

        Principal.add(Part2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-750, 0, 700, 600));

        esquerd_panel.setBackground(new java.awt.Color(0, 255, 255));
        esquerd_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                esquerd_panelMouseEntered(evt);
            }
        });

        titul0.setBackground(new java.awt.Color(0, 0, 0));
        titul0.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        titul0.setForeground(new java.awt.Color(255, 255, 255));
        titul0.setText("Promoções");
        titul0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titul0MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                titul0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                titul0MouseExited(evt);
            }
        });

        javax.swing.GroupLayout esquerd_panelLayout = new javax.swing.GroupLayout(esquerd_panel);
        esquerd_panel.setLayout(esquerd_panelLayout);
        esquerd_panelLayout.setHorizontalGroup(
            esquerd_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, esquerd_panelLayout.createSequentialGroup()
                .addContainerGap(281, Short.MAX_VALUE)
                .addComponent(titul0)
                .addGap(279, 279, 279))
        );
        esquerd_panelLayout.setVerticalGroup(
            esquerd_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, esquerd_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titul0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Principal.add(esquerd_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 60));

        limpar.setBackground(new java.awt.Color(0, 255, 255));
        limpar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        limpar.setForeground(new java.awt.Color(255, 255, 255));
        limpar.setText("Limpar");
        limpar.setBorder(null);
        limpar.setContentAreaFilled(false);
        limpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpar.setOpaque(true);
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });
        Principal.add(limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, 120, 30));

        Tabela.setBackground(new java.awt.Color(0, 0, 0));
        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "ID"
            }
        ));
        Tabela.setColorBackgoundHead(new java.awt.Color(0, 255, 255));
        Tabela.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        Tabela.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        Tabela.setColorSelBackgound(new java.awt.Color(0, 255, 255));
        Tabela.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        Tabela.setFuenteFilas(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Tabela.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Tabela.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Tabela.setGridColor(new java.awt.Color(230, 230, 230));
        Tabela.setOpaque(false);
        Tabela.setRowHeight(20);
        Tabela.setRowMargin(0);
        Tabela.getTableHeader().setReorderingAllowed(false);
        Tabela_scroll.setViewportView(Tabela);

        Principal.add(Tabela_scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 620, 300));

        atualizar.setBackground(new java.awt.Color(0, 255, 255));
        atualizar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        atualizar.setForeground(new java.awt.Color(255, 255, 255));
        atualizar.setText("Atualizar");
        atualizar.setBorder(null);
        atualizar.setContentAreaFilled(false);
        atualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atualizar.setOpaque(true);
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });
        Principal.add(atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pisActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        int position = Part2.getX();

        Animacion.Animacion.mover_izquierda(position,Part2.getWidth()*-1, 1, 50, Part2);
        atualizar.setVisible(true);
        limpar.setVisible(true);
        Tabela.setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed

    }//GEN-LAST:event_alterarActionPerformed

    private void Part2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Part2MouseEntered

    private void titul0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titul0MouseClicked

    }//GEN-LAST:event_titul0MouseClicked

    private void titul0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titul0MouseEntered

    }//GEN-LAST:event_titul0MouseEntered

    private void titul0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titul0MouseExited

    }//GEN-LAST:event_titul0MouseExited

    private void esquerd_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esquerd_panelMouseEntered

    }//GEN-LAST:event_esquerd_panelMouseEntered

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limparActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed

    }//GEN-LAST:event_atualizarActionPerformed

    private void PrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrincipalMouseEntered
        int position = esquerd_panel.getY();
        Animacion.Animacion.subir(position,-60, 1, 5, esquerd_panel);
        if(position != 0){
            esquerd_panel.setVisible(false);
            titul0.setVisible(false);}
    }//GEN-LAST:event_PrincipalMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Part2;
    private javax.swing.JPanel Principal;
    private rojerusan.RSTableMetro Tabela;
    private javax.swing.JScrollPane Tabela_scroll;
    private javax.swing.JButton alterar;
    private javax.swing.JButton atualizar;
    private javax.swing.JTextField cidade;
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JFormattedTextField data_nasc;
    private javax.swing.JTextField email;
    private javax.swing.JPanel esquerd_panel;
    private javax.swing.JTextField estado;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField nome_completo;
    private javax.swing.JFormattedTextField pis;
    private javax.swing.JFormattedTextField rg;
    private javax.swing.JFormattedTextField telefone;
    private javax.swing.JLabel titul0;
    private javax.swing.JLabel titulo_cidade;
    private javax.swing.JLabel titulo_cpf;
    private javax.swing.JLabel titulo_data_nasc;
    private javax.swing.JLabel titulo_email;
    private javax.swing.JLabel titulo_estado;
    private javax.swing.JLabel titulo_nome1;
    private javax.swing.JLabel titulo_pis;
    private javax.swing.JLabel titulo_rg;
    private javax.swing.JLabel titulo_telefone;
    private javax.swing.JTextField usuario;
    private javax.swing.JLabel usuario_text;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
